Algoritmo "exercício_dois"
//Sofia Costa 09/08/2020
Var

          x: inteiro
          y: inteiro
Inicio

//Seção de comandos

    escreval ("Seja bem vindo.")
    escreval ("Digite um número.")
            leia (x)
    escreval ("Agora, por favor, digite outro número.")
            leia (y)


    se (x)>= (y) entao
    escreva ("o maior número é:", x)
    senao
    escreval ("o maior número é:", y)

    fimse

    fimalgoritmo
    
    
