var
DistanciaPercorrida: Inteiro
Combustivel: Inteiro
Tempo: Inteiro

inicio
Escreva("Distancia Percorrida")
Leia (DistanciaPercorrida)

Escreva("Combustivel")
Leia (Combustivel)

Escreva("Tempo (minutos)")
Leia (Tempo)

// aqui ele imprime as formulas antes ditas

Escreva("Consumo Médio:", [B]([/B]DistanciaPercorrida / Combustivel[B])[/B] )

Escreva("Velocidade Média:", [B]([/B]DistanciaPercorrida / (Tempo / 60 )[B])[/B])


fimalgoritmo